Task_1_1_2
TheAndrewLa/oop_tasks pull request #3
Opened 2024-09-17 13:08 UTC by TheAndrewLa

2024-09-17 13:09 UTC, TheAndrewLa commented
Java doc and test weren't done yet. Base classes were created

2024-09-17 15:13 UTC, Sharapov-Maksim requested changes
Доделывайте. Мягкий дедлайн зачтён, хотя и явно не все основные классы были добавлены, игра ведь не состоит только из карт и их колоды

2024-09-17 15:13 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/Card.java
> +        String[] number_names = new String[]{
Такие вспомогательные константные структуры данных не стоит создавать в методе объекта. Их можно разделить между всеми объектами и создавать лишь единожды

2024-09-17 15:13 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/Card.java
> +            name = number_names[rank - 2];
Очень не интуитивное отображение значения карты в имя. Можно, как минимум, воспользоваться `type_names` мапой. Или пары имя - значение объединять внутри объекта

2024-09-17 15:13 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/CardPool.java
> +        cards.add(new Card(rank, CardSuit.Spades));
По объектам из `enum` тоже можно итерироваться, можно получить массив через `CardSuit.values()`

2024-09-24 13:47 UTC, TheAndrewLa commented on Task_1_1_2/src/main/java/andrewla/Card.java
> +        String[] number_names = new String[]{
Сделал

2024-09-24 13:48 UTC, TheAndrewLa commented on Task_1_1_2/src/main/java/andrewla/Card.java
> +            name = number_names[rank - 2];
Не очень понял о чем вы. Но сделал `toString` метод для карты чуть более понятным

2024-09-24 13:48 UTC, TheAndrewLa commented on Task_1_1_2/src/main/java/andrewla/CardPool.java
> +        cards.add(new Card(rank, CardSuit.Spades));
Сделал

2024-09-24 13:48 UTC, TheAndrewLa commented
Доделал до жесткого дедлайна

2024-09-24 15:41 UTC, Sharapov-Maksim requested changes
Замечания выдал
checkstyle у вас не проходит, не забывайте следить за статусом CI

2024-09-24 15:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/Round.java
> +        if (playersHand.getValue() == 21) {
Константу надо выделить в отдельную именованную

2024-09-24 15:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/Round.java
> +    private void playersTurn() {
Добавить тесты. Ввод пользователя можно просимулировать переопределением `InputHandler#scanner` на `new Scanner("n\nY\n ...")`

2024-09-24 15:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/InputHandler.java
> +    private static final Scanner scanner = new Scanner(System.in);
Для тестирования нужно будет сделать метод `init`, в котором можно будет задавать состояние сканера извне

2024-09-24 15:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/Round.java
> +    private void dealersTurn() {
Сделать тесты

2024-09-24 15:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/Round.java
> +    private void playersTurn() {
Чтобы можно было звать из тестовых классов, можно сделать метод `protected`

2024-09-24 15:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/Round.java
> +    public RoundResult play() {
Сделать тесты, переопределив ввод пользователя

2024-09-24 15:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/andrewla/MainTest.java
> +public class MainTest {
Классы тестов должны соответствовать тестируемому классу. Нужно раскидать имеющиеся тесты по разным классам (`CardTest`, `CardPoolTest`, ...)

2024-09-24 15:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/InputHandler.java
> +        return !result.equals("n");
А если пользователь напишет `n    ` или `abrakadabra` метод вернёт положительный ответ. Давайте добавим обработку неверного ввода

2024-09-24 15:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/Card.java
> +            name = number_names[rank - 2];
> Или пары имя - значение объединять внутри объекта

Имелся ввиду `enum` с объектами с двумя полями: имя, значение

> Но сделал toString метод для карты чуть более понятным

Да, так лучше

2024-09-24 15:41 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/andrewla/Hand.java
> +    public void calculateValue() {
Сделать тесты

2024-12-10 05:22 UTC, Sharapov-Maksim approved these changes

2024-12-10 05:22 UTC, merged